Html table
siouxmathware/JuliaStyleGuide.jl pull request #1
Opened 2023-03-31 21:53 UTC by siouxmathware

2023-05-12 13:10 UTC, KeithWM requested changes

2023-05-12 13:10 UTC, KeithWM commented on docs/make_julia_for_numpy_users.jl
> +            np.concatenate((a, b, ...), 1)
This should be 0 right?

2023-05-12 13:10 UTC, KeithWM commented on docs/make_julia_for_numpy_users.jl
> +            concatenate columns of many arrays
This needs a period or parentheses. At the moment the sentence "In Julia [...]  many arrays" is just squashed against the fragment before it.

2023-07-14 11:54 UTC, KeithWM approved these changes

2023-07-14 11:56 UTC, TomLemmensSTN approved these changes

2023-07-14 11:57 UTC, merged